In [7]:
import pandas as pd

data = pd.read_csv('dataset.csv')

display(data)

,Unnamed: 0,NFATC2IP,TXNIP,ZBTB20,OR5L2,HIP1R,EBF1,YTHDC2,RAET1G,ZNRF3,...,GDPD4,PARD3,GRIN2B,ENO2,IRF4,KCNJ4,PPM1G,KRT27,DNAJB8,IMMT
0,brca1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,brca2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,brca3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,brca4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,brca5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2059,luad558,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2060,luad559,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2061,luad560,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2062,luad561,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2063,luad562,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [8]:
# og number of rows 
print(data.shape)

# drop NAN values
# Pandas function : "Drop the rows where at least one element is missing."
data = data.dropna()
#print data sizes so we can see if we dropped any rows 
print(data.shape)

# drop duplicates
# Pandas function : "By default, it removes duplicate rows based on all columns."
data = data.drop_duplicates()
# print data sizes so we can see if we dropped any rows
print(data.shape)

(2064, 12214)
(2064, 12214)
(2064, 12214)

In [9]:
# find all the different types of samples and seperate them into their own dataframes

# print(data.iloc[:, 0])


breast_cancer = data[data.iloc[:, 0].str.startswith('brca')]

display(breast_cancer)

prostate_cancer = data[data.iloc[:, 0].str.startswith('prad')]

display(prostate_cancer)

lung_cancer = data[data.iloc[:, 0].str.startswith('luad')]

display(lung_cancer)

,Unnamed: 0,NFATC2IP,TXNIP,ZBTB20,OR5L2,HIP1R,EBF1,YTHDC2,RAET1G,ZNRF3,...,GDPD4,PARD3,GRIN2B,ENO2,IRF4,KCNJ4,PPM1G,KRT27,DNAJB8,IMMT
0,brca1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,brca2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,brca3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,brca4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,brca5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1004,brca1005,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1005,brca1006,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1006,brca1007,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1007,brca1008,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1008,brca1009,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

,Unnamed: 0,NFATC2IP,TXNIP,ZBTB20,OR5L2,HIP1R,EBF1,YTHDC2,RAET1G,ZNRF3,...,GDPD4,PARD3,GRIN2B,ENO2,IRF4,KCNJ4,PPM1G,KRT27,DNAJB8,IMMT
1009,prad1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1010,prad2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1011,prad3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1012,prad4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1013,prad5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1497,prad489,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1498,prad490,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1499,prad491,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1500,prad492,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1501,prad493,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

,Unnamed: 0,NFATC2IP,TXNIP,ZBTB20,OR5L2,HIP1R,EBF1,YTHDC2,RAET1G,ZNRF3,...,GDPD4,PARD3,GRIN2B,ENO2,IRF4,KCNJ4,PPM1G,KRT27,DNAJB8,IMMT
1502,luad1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1503,luad2,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1504,luad3,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1505,luad4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1506,luad5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2059,luad558,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2060,luad559,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2061,luad560,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2062,luad561,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2063,luad562,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0